spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

